### ISSUE TITLE
Errors in pair_train.py : version ?

### ISSUE THREAD

**Issue by Sousouam** [ahangchen/rank-reid#14]
I got lots of error when running pair_train.py.
Error : range object does not support item assignment

My environment is the tensorflow-gpu 1.11.0 keras 2.1.6 python 3.6
What is the environment of yours ?

**Comment by ahangchen** [comment]
tensorFlow-gpu 1.8
keras 2.1.5
python 2.7.11

**Comment by Sousouam** [comment]
> tensorFlow-gpu 1.8
> keras 2.1.5
> python 2.7.11

thank you @ahangchen for your replay. 
I still have errors when running pair_train.py 
Now the error is 

from keras.backend import set_session
InportError : cannot import name set_session 

any idea to solve it ?

**Comment by ahangchen** [comment]
set_session is used for allow_growth setting, you can remove them without affecting the results.

**Comment by Sousouam** [comment]
Thank you @ahangchen for your replay !
