### ISSUE TITLE
作者大大，我下载的数据集之后和你要求的对不上

### ISSUE THREAD

**Issue by HMS97** [ahangchen/rank-reid#15]
![_20181207230850](https://user-images.githubusercontent.com/27955693/49655325-5e005d80-fa75-11e8-8528-ee54db770118.jpg)
我下载之后是这样的，我吧query改成了probe，然后修改路径执行
仍然报错。
似乎是找不到list里的图片。

**Comment by ahangchen** [comment]
- bounding_box_train改成train;
- bounding_box_test改成test；
- query改成probe；
