### ISSUE TITLE
simple_rank_transfer.py是什么作用？

### ISSUE THREAD

**Issue by Julius-ZCJ** [ahangchen/rank-reid#17]
作者大大，本人最近新入坑，最近在复现你的代码，但是在实现过程中有点疑问，想问下simple_rank_transfer.py具体是什么作用？题主的解释有点简单，有点不理解

**Comment by ahangchen** [comment]
是我们CVPR代码里的一个transfer learning模块，感兴趣的话可以看我的这篇[解读](https://zhuanlan.zhihu.com/p/34778414)
