### ISSUE TITLE
what is the version of your code?

### ISSUE THREAD

**Issue by JackeyWang777** [ahangchen/rank-reid#3]
I got lots of error in the code.
My environment is the tensorflow-gpu 1.2.0 keras 2.1.5   python 3.6.2
What is the environment of yours

**Comment by JackeyWang777** [comment]
Maybe python 2.7

**Comment by ahangchen** [comment]
Your keras and tensorflow is not fit. I finish the experiment with python2.7, tensorflow 1.4 and keras 2.1.5. Now I'm adjusting the code for newest tensorflow and keras.
