### ISSUE TITLE
cross_filter_pid.log not found

### ISSUE THREAD

**Issue by 532091602hzy** [ahangchen/rank-reid#4]
Hi, after training the baseline, I try to run the evaluate.py to evaluate the baseline model, then an exception is thrown: IOError: cross_filter_pid.log not found. But I can't find anything about 'cross_filter_pid.log' in the code, how to solve this problem? thanks

**Comment by ahangchen** [comment]
cross_filter_pid is a file generated by TrackViz/st_filter.py in Spatial Temporal Fusion.
If you only want to evaluate the accuracy of ResNet52 Visual Classifier, you need to:
- train the baseline, 
- use the baseline model to evaluate on target Dataset,  specifying a path of your output file, and
- compute the accuracy with corresponding function evaluate.py on the path you just specified.

**Comment by 532091602hzy** [comment]
OK, I will try it again, thanks for your answer
