### ISSUE TITLE
Rank 5, rank 10, rank 20 accuracy

### ISSUE THREAD

**Issue by jpainam** [ahangchen/rank-reid#6]
Hi!
I have modified your evaluation code to output the other rank accuracy but always get inaccurate values. Here is the code,
Initilize CMC with zero value
` CMC = np.zeros([len(query_info), len(test_info)])`
In the for loop
```python
if ig_cnt >= YES[0]:
   rank_1 += 1
   CMC[idx, ig_cnt:] = 1
   rank1_list.append(1)
else:
   CMC[idx, ig_cnt:] = 0
   rank1_list.append(0)
```
After the loop
```python
rank_1 = np.mean(CMC[:, 0])
rank_5 = np.mean(CMC[:, 4])
rank_10 = np.mean(CMC[:, 9])
rank_20 = np.mean(CMC[:, 19])
```
But here is the output
```python
Rank 1: 0.000000
Rank 5: 0.685451
Rank 10: 0.745362
Rank 20: 0.758890
```
Kindly look at the code and tell what i'm doing wrong?
Thanks

**Comment by ahangchen** [comment]
I guess you modify the code referring to [Market1501 evaluation code](https://github.com/layumi/DukeMTMC-reID_evaluation). However, the evaluation function in this repository is written for higher efficiency thus there are some logical differences. As a result, `ig_cnt >= YES[0]` only means top1 item is shot, and it can't be use to determine cmc[*, k]. 

Actually, for rank5, rank10, rank20 accuracy,  there is some simpler ways to implement. I will update the code and notify you here soon.

**Comment by ahangchen** [comment]
@jpainam Please refer to [this](https://github.com/ahangchen/rank-reid/blob/dev/baseline/evaluate.py#L133), it will output the same result as  [Market1501 evaluation code](https://github.com/layumi/DukeMTMC-reID_evaluation).

**Comment by jpainam** [comment]
Thank for pointing this `ig_cnt >= YES[0]` out. I will modify the code according to [this](https://github.com/hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning/blob/master/PUL/evaluate.py)

**Comment by jpainam** [comment]
Thank for [this](https://github.com/ahangchen/rank-reid/blob/dev/baseline/evaluate.py#L133)
