### ISSUE TITLE
请问rank-reid/baseline/evaluate.py 中cross_filter_pid.log文件是什么？

### ISSUE THREAD

**Issue by TTLuze** [ahangchen/rank-reid#9]
作者您好，我在看您复现的keras代码，即rank-reid/baseline/evaluate.py，代码中导入了一个文件cross_filter_pid.log，这个在项目和market-1501数据集里都没有，请问这个是您自定义的文件吗？

**Comment by ahangchen** [comment]
是的，这个是预测出来的根据相似度排序的id矩阵，可以根据这个矩阵计算准确率和mAP
